apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
spec:
  selector:
    matchLabels:
      app: voting-app
  replicas: 2
  template:
    metadata:
      labels:
        app: voting-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: voting-app
        image: ghcr.io/frenzywall/voting-app:v1.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: redis
        resources:
          requests:
            memory: "50Mi"  
            cpu: "100m"    
          limits:
            memory: "100Mi"  
            cpu: "205m"      
