apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
spec:
  selector:
    matchLabels:
      app: voting-app
  replicas: 4
  template:
    metadata:
      labels:
        app: voting-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: voting-app
        image: sreeramjvp/voting-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: redis
        resources:
          requests:
            memory: "128Mi"    
            cpu: "200m"        
          limits:
            memory: "256Mi"   
            cpu: "500m"       
