apiVersion: v1
kind: Service
metadata:
  name: redisinsight
spec:
  type: NodePort
  selector:
    app: redisinsight
  ports:
    - port: 5540        
      targetPort: 5540   
      nodePort: 30081    
