apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
spec:
  selector:
    matchLabels:
      app: redisinsight
  replicas: 1
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
      - name: redisinsight
        image: redislabs/redisinsight:2.64
        ports:
        - containerPort: 5540
---
